package com.pedro.racasclasses.client.gui;

import java.util.List;

public record RaceOption(
        String id,
        String name,
        String summary,
        String attributes,
        List<String> abilities,
        List<String> weaknesses,
        List<String> subraces
) {
    public static final List<RaceOption> ALL = List.of(
            race("humano", "Humano", "Uma origem equilibrada, sem vantagens ou fraquezas raciais.",
                    "20 HP  •  velocidade normal  •  tamanho normal", List.of("Sem habilidades raciais"), List.of(), List.of()),
            race("dragonborn", "Draconato", "Resistente e ofensivo, com uma baforada ligada à ancestralidade.",
                    "22 HP  •  +0,2 dano  •  +2 armadura  •  visão noturna",
                    List.of("Baforada elemental: /raca breath", "75% de resistência ao próprio elemento"),
                    List.of("Fraqueza ao elemento oposto: Fogo ↔ Poison, Gelo ↔ Fogo, Raio ↔ Fogo, Ácido ↔ Raio (depende da ancestralidade)"), List.of("Vermelho", "Dourado", "Latão", "Branco", "Prateado", "Azul", "Bronze", "Negro", "Cobre", "Verde")),
            race("dwarf", "Anão", "Minerador resistente, lento e difícil de envenenar.",
                    "24 HP  •  90% velocidade  •  60% tamanho  •  visão noturna",
                    List.of("+20% velocidade de mineração", "3% de chance de fundir minério ao quebrar", "50% de resistência a veneno"),
                    List.of("Impedimento na água: não consegue nadar (aplica Slowness IV)"), List.of()),
            race("elf", "Elfo", "Arqueiro adaptado à floresta ou à escuridão.",
                    "20 HP  •  visão noturna", List.of("+25% dano com flechas", "Bônus ambientais dependem da sub-raça"),
                    List.of("Wood Elf: +50% dano de fogo e fraqueza sem folhagem", "Drow: +50% dano no sol + Weakness + Darkness"), List.of("Elfo da Floresta", "Drow")),
            race("gnome", "Gnomo", "Pequeno explorador, protegido contra quedas ou criaturas específicas.",
                    "20 HP  •  90% velocidade  •  60% tamanho  •  visão noturna",
                    List.of("Rocha: reduz 3 blocos de queda", "Floresta: animais, lobos e aranhas não miram em você"),
                    List.of("Forest Gnome: +50% dano de fogo", "Rock Gnome: +30% dano de explosão e impedimento na água"), List.of("Gnomo da Floresta", "Gnomo da Rocha")),
            race("halfelf", "Meio-Elfo", "Explorador versátil que prospera em florestas e na água.",
                    "22 HP  •  visão noturna", List.of("Invisibilidade perto de folhagem", "+10% XP de criaturas", "+15% eficiência na água"),
                    List.of("Fome 15% mais rápida"), List.of()),
            race("halforc", "Meio-Orc", "Combatente intimidador com golpes críticos fortes.",
                    "24 HP  •  +0,2 dano  •  110% tamanho  •  visão noturna",
                    List.of("+20% dano crítico", "Esqueletos evitam e fogem de você"),
                    List.of("+30% dano de magia"), List.of()),
            race("aarakocra", "Aarakocra", "Combatente alado com garras e grande mobilidade vertical.",
                    "20 HP  •  velocidade normal", List.of("Elytra racial permanente", "+3 dano desarmado", "R: super pulo, recarga de 10s"),
                    List.of("+50% dano de queda", "Não pode usar peitoral no lugar da elytra"), List.of()),
            race("halfling", "Halfling", "Pequeno, sortudo e resistente a efeitos debilitantes.",
                    "20 HP  •  90% velocidade  •  55% tamanho",
                    List.of("10% de chance de duplicar drops de blocos", "Imune a fraqueza e lentidão", "Pé Leve: furtividade; Robusto: +6 HP e resistência física"),
                    List.of("Lightfoot: Fome 25% mais rápida", "Stout: +25% dano de veneno e impedimento na água"), List.of("Pé Leve", "Robusto")),
            race("tiefling", "Tiefling", "Herança infernal com alta resistência ao fogo.",
                    "20 HP  •  visão noturna", List.of("75% de resistência ao fogo", "Ataques desarmados aplicam efeito da linhagem"),
                    List.of("+30% dano sagrado (MAGIC)", "Asmodeus: fraqueza a gelo, Levistus: fraqueza a fogo, Zariel: fraqueza a magia"), List.of("Asmodeus", "Levistus", "Zariel")),
            race("aasimar", "Aasimar", "Guerreiro celestial alado capaz de se curar.",
                    "24 HP  •  visão noturna", List.of("+20% dano corpo a corpo", "Elytra permanente", "H: cura 4 corações", "R: super pulo"),
                    List.of("+50% dano de fogo (elemento oposto ao celestial)", "+20% dano de armas"), List.of()),
            race("goliath", "Goliath", "Tanque enorme, muito forte e difícil de empurrar.",
                    "28 HP  •  +0,3 dano  •  70% velocidade  •  150% tamanho",
                    List.of("50% resistência a empurrão", "H: grande resistência por 10s", "Ignora 5 blocos de queda"),
                    List.of("+30% dano de explosão (vulnerabilidade devido ao tamanho)"), List.of()),
            race("tabaxi", "Tabaxi", "Caçador extremamente ágil com garras naturais.",
                    "20 HP  •  120% velocidade  •  visão noturna", List.of("+2 dano desarmado", "H: velocidade III por 5s", "Imune a dano de queda"),
                    List.of("Sofre 1 dano/tick na água (hidrofobia)"), List.of()),
            race("triton", "Triton", "Especialista aquático que ganha força quando submerso.",
                    "22 HP  •  tamanho normal", List.of("Respiração, visão, pressa e graça do golfinho na água", "+20% dano com tridente", "50% resistência a congelamento"),
                    List.of("+50% dano de fogo (elemento oposto à água)"), List.of()),
            race("orc", "Orc", "Brutamontes resistente em combate próximo, aliado dos mortos-vivos.",
                    "24 HP  •  130% tamanho  •  visão noturna", List.of("H: velocidade, força II e cura", "+10% dano contra criaturas", "15% resistência corpo a corpo"),
                    List.of("+50% dano de fogo, raio e magia (elementos opostos à resistência física)"), List.of()),
            race("goblin", "Goblin", "Furtivo, pequeno e rápido, mas frágil contra armas.",
                    "18 HP  •  120% velocidade  •  65% tamanho  •  visão noturna",
                    List.of("H: invisibilidade por 10s", "Mais rápido ao agachar", "30% resistência mágica"),
                    List.of("+30% dano de armas"), List.of()),
            race("hobgoblin", "Hobgoblin", "Soldado marcial especializado em espadas e machados.",
                    "22 HP  •  +0,1 dano  •  visão noturna", List.of("+30% dano com espada ou machado", "H: força I por 10s"),
                    List.of("+30% dano de magia"), List.of()),
            race("lizardfolk", "Lizardfolk", "Predador aquático de couro resistente.",
                    "22 HP  •  +4 armadura", List.of("+3 dano desarmado", "+50% eficiência na água", "Cura 1 coração ao matar uma criatura"),
                    List.of("+75% dano de lava (elemento oposto à água)"), List.of()),
            race("minotaur", "Minotauro", "Investidor pesado que causa mais dano enquanto corre.",
                    "24 HP  •  +0,2 dano  •  120% tamanho", List.of("Ataques empurram mais", "+30% dano correndo", "15% redução geral", "H: velocidade II"),
                    List.of("+30% dano perfurante (vulnerabilidade devido ao tamanho)"), List.of()),
            race("firbolg", "Firbolg", "Guardião da floresta com furtividade e afinidade animal.",
                    "22 HP  •  120% tamanho  •  visão noturna", List.of("Velocidade e regeneração perto de folhas", "H: invisibilidade por 5s", "Doma animais domesticáveis com a mão vazia"),
                    List.of("+50% dano de fogo (elemento oposto à natureza)"), List.of()),
            race("kobold", "Kobold", "Pequeno combatente dracônico que trabalha melhor em grupo.",
                    "16 HP  •  120% velocidade  •  50% tamanho  •  visão noturna", List.of("+10% dano com aliado próximo", "H: força e regeneração"),
                    List.of("Fraqueza e +30% dano recebido sob o sol (sensibilidade à luz)"), List.of()),
            race("leonin", "Leonin", "Caçador carnívoro veloz, equipado com garras e rugido.",
                    "22 HP  •  +0,1 dano  •  110% velocidade  •  110% tamanho", List.of("+3 dano desarmado", "H: força III por 10s"),
                    List.of("Só come carne", "Fome 30% mais rápida"), List.of()),
            race("satyr", "Sátiro", "Trapaceiro mágico veloz, fortalecido por música.",
                    "20 HP  •  110% velocidade  •  85% tamanho", List.of("Velocidade I constante", "30% resistência mágica", "R: super pulo", "H: enfraquece criaturas próximas"),
                    List.of("+30% dano de armas de ferro (metal ferroeiro)"), List.of()),
            race("tortle", "Tortle", "Fortaleza ambulante com casco natural e respiração aquática.",
                    "26 HP  •  90% velocidade  •  110% tamanho", List.of("60% redução geral de dano", "H: defesa do casco", "Respiração aquática"),
                    List.of("+30% dano de fogo", "Velocidade reduzida (0.06)", "Não pode equipar armaduras"), List.of()),
            race("verdan", "Verdan", "Sobrevivente regenerativo com resistência sobrenatural.",
                    "22 HP  •  tamanho normal", List.of("20% resistência mágica", "Cura 1 coração ao sofrer dano, recarga de 30s", "Regenera lentamente com vida crítica"),
                    List.of("+30% dano de magia"), List.of()),
            race("quacho", "Quacho", "Anfíbio venenoso, pequeno e resistente.",
                    "18 HP  •  110% velocidade  •  65% tamanho", List.of("Respiração aquática", "Imune a veneno", "Envenena quem o ataca", "10% redução geral"),
                    List.of("+30% dano de fogo e lava (elemento oposto à água)"), List.of()),
            race("githyanki", "Githyanki", "Guerreiro astral resistente à magia e capaz de se reposicionar instantaneamente.",
                    "22 HP  •  +0,2 dano  •  +1 armadura  •  visão noturna",
                    List.of("30% de resistência a dano mágico", "H: Misty Step com pérola rápida", "Imunidade à queda após o teleporte"),
                    List.of("+30% dano mágico"), List.of()),
            race("kenku", "Kenku", "Imitador furtivo que se mistura às sombras e confunde criaturas com sons.",
                    "20 HP  •  110% velocidade  •  visão noturna",
                    List.of("Invisibilidade enquanto agachado", "H: imita um som de criatura", "Illagers não atacam"),
                    List.of("Villagers recusam trocas", "+30% dano de projéteis"), List.of()),
            race("harengon", "Harengon", "Explorador pequeno, veloz e sortudo, especializado em grandes saltos.",
                    "20 HP  •  110% velocidade  •  85% tamanho  •  visão noturna",
                    List.of("R: super pulo, recarga de 8s", "Ignora 5 blocos de queda", "30% de chance de drop extra de criaturas"),
                    List.of("+50% dano de fogo (elemento oposto à agilidade)"), List.of()),
            race("yuanti", "Yuan-Ti", "Serpente humanoide imune a venenos e resistente a magia.",
                    "22 HP  •  visão noturna", List.of("Imune a veneno", "30% resistência mágica", "H: Poison Spray"),
                    List.of("+30% dano de mobs mortos-vivos"), List.of()),
            race("kender", "Kender", "Pequeno aventureiro curioso, furtivo e extraordinariamente sortudo.",
                    "20 HP  •  110% velocidade  •  85% tamanho", List.of("15% de drop extra", "Invisível ao agachar", "H: Taunt"),
                    List.of("Fome 25% mais rápida"), List.of()),
            race("khenra", "Khenra", "Guerreiro felino veloz que encadeia golpes contra o mesmo alvo.",
                    "22 HP  •  +0,1 dano  •  110% velocidade  •  visão noturna", List.of("Velocidade I constante", "Segundo golpe: +20% dano", "H: Twin Fury"),
                    List.of("+50% dano de fogo (elemento oposto à agilidade)"), List.of()),
            race("warforged", "Warforged", "Construto resiliente que não precisa comer.",
                    "24 HP  •  90% velocidade  •  110% tamanho  •  +2 armadura", List.of("Fome sempre cheia", "Regeneração I", "H: Integrated Protection"),
                    List.of("+30% dano de raio"), List.of()),
            race("vampire", "Vampiro", "Predador noturno que se nutre de seus inimigos.",
                    "20 HP  •  +0,1 dano  •  110% velocidade  •  visão noturna", List.of("Mordida desarmada cura", "H: Blood Drain", "Fome 20% mais lenta"),
                    List.of("Fraqueza e lentidão sob o sol", "Não pode comer nada (só drenagem)"), List.of()),
            race("changeling", "Changeling", "Metamorfo capaz de se ocultar por meio de uma aparência ilusória.",
                    "20 HP  •  110% velocidade", List.of("H: Disguise Self (invisibilidade)"),
                    List.of("+30% dano de magia"), List.of()),
            race("siren", "Sereia", "Cantora aquática que controla os inimigos com sua melodia.",
                    "20 HP  •  visão noturna  •  +30% nado", List.of("Respiração aquática", "H: Charming Song"),
                    List.of("+50% dano de fogo"), List.of()),
            race("hadozee", "Hadozee", "Ágil escalador que plana lentamente entre as alturas.",
                    "22 HP  •  110% velocidade  •  105% tamanho  •  visão noturna", List.of("Queda lenta", "Escala paredes agachado", "H: Glide"),
                    List.of("+30% dano perfurante"), List.of()),
            race("giff", "Giff", "Hipopótamo marcial pesado, resistente a empurrões e mestre da besta.",
                    "26 HP  •  +0,1 dano  •  90% velocidade  •  120% tamanho  •  +2 armadura", List.of("50% resistência a empurrão", "+20% dano de besta", "H: Headbutt"),
                    List.of("+30% dano de explosão"), List.of()),
            race("shifter", "Shifter", "Bestial que entra em fúria curta e troca o poder especial pela linhagem.",
                    "22 HP  •  110% velocidade  •  visão noturna",
                    List.of("H: Shifting por 30s", "Segundo H durante o shift usa o poder da linhagem"),
                    List.of("+30% dano de armas de ferro (metal ferroeiro)"), List.of("Longtooth", "Razorclaw", "Wildhunt")),
            race("vedalken", "Vedalken", "Estudioso resistente à magia, com percepção arcana aguçada.",
                    "20 HP  •  visão noturna", List.of("30% resistência mágica", "+10% XP de criaturas", "H: Arcane Insight"),
                    List.of("+30% dano físico (trade-off pela resistência mágica)"), List.of()),
            race("hexblood", "Hexblood", "Marcado por bruxaria: devolve náusea e amaldiçoa um alvo.",
                    "20 HP  •  visão noturna", List.of("20% resistência mágica removida", "Atacante corpo a corpo recebe náusea", "H: Hex"),
                    List.of("+30% dano sagrado (MAGIC)"), List.of()),
            race("reborn", "Reborn", "Corpo reconstruído que não precisa respirar como os vivos.",
                    "22 HP  •  visão noturna", List.of("Respiração aquática", "50% resistência a veneno", "+10% XP", "H: Deathly Resilience"),
                    List.of("+50% dano de fogo (elemento oposto à reconstrução)"), List.of()),
            race("plasmoid", "Plasmoid", "Gosma humanoide amorfa, imune a veneno.",
                    "22 HP  •  70% tamanho  •  visão noturna", List.of("Respiração aquática", "Imune a veneno", "H: Amorphous"),
                    List.of("+50% dano de gelo (elemento oposto à forma amorfa)"), List.of()),
            race("genasi", "Genasi", "Herdeiro elemental; o corpo muda com ar, fogo, terra ou água.",
                    "22 HP  •  atributos variam com o elemento", List.of("Habilidade H e passivas dependem do elemento"),
                    List.of("Ar: +30% dano de explosão", "Fogo: +50% dano na água e chuva (elemento oposto)", "Terra: +30% dano de explosão", "Água: +50% dano de fogo (elemento oposto)"), List.of("Ar", "Fogo", "Terra", "Água")),
            race("naga", "Naga", "Serpente constritora, venenosa e à vontade na água.",
                    "22 HP  •  +3 armadura  •  visão noturna  •  +50% nado",
                    List.of("Respiração aquática", "Mão vazia aplica veneno", "H: Constrict"),
                    List.of("+30% dano de mobs mortos-vivos (resistência à vida natural)"), List.of()),
            race("kalashtar", "Kalashtar", "Mente compartilhada, resistente a magia e capaz de sentir aliados.",
                    "22 HP  •  visão noturna", List.of("50% resistência mágica", "Imune a náusea", "Telepatia ao agachar", "H: Mind Link"),
                    List.of("+30% dano físico (trade-off pela resistência mágica)"), List.of()),
            race("simichybrid", "Simic Hybrid", "Mutante de laboratório com adaptação corporal.",
                    "22 HP  •  visão noturna", List.of("H: Adaptive Shield", "Passiva depende da mutação"),
                    List.of("+30% dano de magia (trade-off pela adaptabilidade)"), List.of("Manta Glide", "Climbing", "Grappling")),
            race("loxodon", "Loxodon", "Elefante tanque, lento e pesado, com tromba devastadora.",
                    "28 HP  •  +0,1 dano  •  80% velocidade  •  130% tamanho  •  +4 armadura  •  visão noturna",
                    List.of("+2 dano desarmado", "Ignora 3 blocos de queda", "H: Trunk Slam"),
                    List.of("+30% dano de explosão (vulnerabilidade devido ao tamanho)"), List.of()),
            race("centaur", "Centaur", "Corredor de cascos pesados que investe contra o alvo.",
                    "24 HP  •  +0,1 dano  •  120% velocidade  •  115% tamanho",
                    List.of("+2 dano desarmado", "Ignora 2 blocos de queda", "H: Charge"),
                    List.of("+30% dano perfurante (vulnerabilidade devido ao tamanho)"), List.of()),
            race("fungril", "Fungril", "Humanoide fúngico que envenena o entorno e solta nuvens de esporos.",
                    "22 HP  •  80% velocidade  •  105% tamanho  •  +3 armadura  •  visão noturna",
                    List.of("Aura de veneno", "H: Spore Cloud"),
                    List.of("+50% dano de fogo (elemento oposto ao fungo)"), List.of()),
            race("wukong", "Wukong", "Macaco guerreiro ágil, com pulo extra e hidrofobia.",
                    "22 HP  •  +0,2 dano  •  110% velocidade  •  visão noturna",
                    List.of("+2 dano desarmado", "Escala paredes agachado", "H: Rugido"),
                    List.of("Sofre 1 dano/tick na água (hidrofobia)", "+30% dano de raio (elemento oposto)"), List.of()),
            race("drider", "Drider", "Meio-aracnídeo das profundezas, aliado das aranhas.",
                    "22 HP  •  +0,2 dano  •  visão noturna", List.of("Escala paredes agachado", "Aranhas não atacam", "H: Teia", "Fome 20% mais lenta"),
                    List.of("Só come carne", "+50% dano de fogo"), List.of())
    );

    private static RaceOption race(String id, String name, String summary, String attributes, List<String> abilities) {
        return race(id, name, summary, attributes, abilities, List.of(), List.of());
    }

    private static RaceOption race(String id, String name, String summary, String attributes,
                                   List<String> abilities, List<String> weaknesses, List<String> subraces) {
        return new RaceOption(id, name, summary, attributes, abilities, weaknesses, subraces);
    }
}
