package com.pedro.racasclasses.client.gui;

import java.util.List;

public record RaceOption(
        String id,
        String name,
        String summary,
        String attributes,
        List<String> abilities,
        List<String> weaknesses,
        List<String> subraces
) {
    public static final List<RaceOption> ALL = List.of(
            race("humano", "Humano", "Uma origem equilibrada, sem vantagens ou fraquezas raciais.",
                    "20 HP  •  velocidade normal  •  tamanho normal", List.of("Sem habilidades raciais")),
            race("dragonborn", "Draconato", "Resistente e ofensivo, com uma baforada ligada à ancestralidade sorteada.",
                    "22 HP  •  +0,2 dano  •  +2 armadura  •  visão noturna",
                    List.of("Baforada elemental: /raca breath", "75% de resistência ao próprio elemento"),
                    List.of(), List.of("Vermelho", "Dourado", "Latão", "Branco", "Prateado", "Azul", "Bronze", "Negro", "Cobre", "Verde")),
            race("dwarf", "Anão", "Minerador resistente, lento e difícil de envenenar.",
                    "24 HP  •  90% velocidade  •  60% tamanho  •  visão noturna",
                    List.of("+20% velocidade de mineração", "3% de chance de fundir minério ao quebrar", "50% de resistência a veneno")),
            race("elf", "Elfo", "Arqueiro adaptado à floresta ou à escuridão.",
                    "20 HP  •  visão noturna", List.of("+25% dano com flechas", "Bônus ambientais dependem da sub-raça"),
                    List.of(), List.of("Elfo da Floresta", "Drow")),
            race("gnome", "Gnomo", "Pequeno explorador, protegido contra quedas ou criaturas específicas.",
                    "20 HP  •  90% velocidade  •  60% tamanho  •  visão noturna",
                    List.of("Rocha: reduz 3 blocos de queda", "Floresta: animais, lobos e aranhas não miram em você"),
                    List.of(), List.of("Gnomo da Floresta", "Gnomo da Rocha")),
            race("halfelf", "Meio-Elfo", "Explorador versátil que prospera em florestas e na água.",
                    "22 HP  •  visão noturna", List.of("Invisibilidade perto de folhagem", "+10% XP de criaturas", "+15% eficiência na água")),
            race("halforc", "Meio-Orc", "Combatente intimidador com golpes críticos fortes.",
                    "24 HP  •  +0,2 dano  •  110% tamanho  •  visão noturna",
                    List.of("+20% dano crítico", "Esqueletos evitam e fogem de você")),
            race("aarakocra", "Aarakocra", "Combatente alado com garras e grande mobilidade vertical.",
                    "20 HP  •  velocidade normal", List.of("Elytra racial permanente", "+3 dano desarmado", "R: super pulo, recarga de 10s"),
                    List.of("Não pode usar peitoral no lugar da elytra"), List.of()),
            race("halfling", "Halfling", "Pequeno, sortudo e resistente a efeitos debilitantes.",
                    "20 HP  •  90% velocidade  •  55% tamanho",
                    List.of("10% de chance de duplicar drops de blocos", "Imune a fraqueza e lentidão", "Pé Leve: furtividade; Robusto: +6 HP e resistência física"),
                    List.of(), List.of("Pé Leve", "Robusto")),
            race("tiefling", "Tiefling", "Herança infernal com alta resistência ao fogo.",
                    "20 HP  •  visão noturna", List.of("75% de resistência ao fogo", "Ataques desarmados aplicam efeito da linhagem"),
                    List.of(), List.of("Asmodeus", "Levistus", "Zariel")),
            race("aasimar", "Aasimar", "Guerreiro celestial alado capaz de se curar.",
                    "24 HP  •  visão noturna", List.of("+20% dano corpo a corpo", "Elytra permanente", "H: cura 4 corações", "R: super pulo"),
                    List.of("+50% dano de fogo", "+20% dano de armas"), List.of()),
            race("goliath", "Goliath", "Tanque enorme, muito forte e difícil de empurrar.",
                    "28 HP  •  +0,3 dano  •  70% velocidade  •  150% tamanho",
                    List.of("50% resistência a empurrão", "H: grande resistência por 10s", "Ignora 5 blocos de queda")),
            race("tabaxi", "Tabaxi", "Caçador extremamente ágil com garras naturais.",
                    "20 HP  •  120% velocidade  •  visão noturna", List.of("+2 dano desarmado", "H: velocidade III por 5s", "Imune a dano de queda"),
                    List.of("Sofre dano dentro da água"), List.of()),
            race("triton", "Triton", "Especialista aquático que ganha força quando submerso.",
                    "22 HP  •  tamanho normal", List.of("Respiração, visão, pressa e graça do golfinho na água", "+20% dano com tridente", "50% resistência a congelamento")),
            race("orc", "Orc", "Brutamontes resistente em combate próximo, aliado dos mortos-vivos.",
                    "24 HP  •  130% tamanho  •  visão noturna", List.of("H: velocidade, força II e cura", "+10% dano contra criaturas", "15% resistência corpo a corpo"),
                    List.of("+50% dano de fogo, raio e magia"), List.of()),
            race("goblin", "Goblin", "Furtivo, pequeno e rápido, mas frágil contra armas.",
                    "18 HP  •  120% velocidade  •  65% tamanho  •  visão noturna",
                    List.of("H: invisibilidade por 10s", "Mais rápido ao agachar", "30% resistência mágica"),
                    List.of("+20% dano de armas"), List.of()),
            race("hobgoblin", "Hobgoblin", "Soldado marcial especializado em espadas e machados.",
                    "22 HP  •  +0,1 dano  •  visão noturna", List.of("+30% dano com espada ou machado", "H: força I por 10s")),
            race("lizardfolk", "Lizardfolk", "Predador aquático de couro resistente.",
                    "22 HP  •  +4 armadura", List.of("+3 dano desarmado", "+50% eficiência na água", "Cura 1 coração ao matar uma criatura"),
                    List.of("+75% dano de lava"), List.of()),
            race("minotaur", "Minotauro", "Investidor pesado que causa mais dano enquanto corre.",
                    "24 HP  •  +0,2 dano  •  120% tamanho", List.of("Ataques empurram mais", "+30% dano correndo", "15% redução geral", "H: velocidade II")),
            race("firbolg", "Firbolg", "Guardião da floresta com furtividade e afinidade animal.",
                    "22 HP  •  120% tamanho  •  visão noturna", List.of("Velocidade e regeneração perto de folhas", "H: invisibilidade por 5s", "Doma animais domesticáveis com a mão vazia")),
            race("kobold", "Kobold", "Pequeno combatente dracônico que trabalha melhor em grupo.",
                    "16 HP  •  120% velocidade  •  50% tamanho  •  visão noturna", List.of("+10% dano com aliado próximo", "H: força e regeneração"),
                    List.of("Fraqueza e +20% dano recebido sob o sol"), List.of()),
            race("leonin", "Leonin", "Caçador carnívoro veloz, equipado com garras e rugido.",
                    "22 HP  •  +0,1 dano  •  110% velocidade  •  110% tamanho", List.of("+3 dano desarmado", "H: força III por 10s"),
                    List.of("Só come carne", "Fome aumenta mais rapidamente"), List.of()),
            race("satyr", "Sátiro", "Trapaceiro mágico veloz, fortalecido por música.",
                    "20 HP  •  110% velocidade  •  85% tamanho", List.of("Velocidade I constante", "30% resistência mágica", "R: super pulo", "H: enfraquece criaturas próximas")),
            race("tortle", "Tortle", "Fortaleza ambulante com casco natural e respiração aquática.",
                    "26 HP  •  90% velocidade  •  110% tamanho", List.of("60% redução geral de dano", "H: defesa do casco", "Respiração aquática"),
                    List.of("Não pode equipar armaduras"), List.of()),
            race("verdan", "Verdan", "Sobrevivente regenerativo com resistência sobrenatural.",
                    "22 HP  •  tamanho normal", List.of("20% resistência mágica", "Cura 1 coração ao sofrer dano, recarga de 30s", "Regenera lentamente com vida crítica")),
            race("quacho", "Quacho", "Anfíbio venenoso, pequeno e resistente.",
                    "18 HP  •  110% velocidade  •  65% tamanho", List.of("Respiração aquática", "Imune a veneno", "Envenena quem o ataca", "10% redução geral"),
                    List.of("+30% dano de fogo"), List.of()),
            race("githyanki", "Githyanki", "Guerreiro astral resistente à magia e capaz de se reposicionar instantaneamente.",
                    "22 HP  •  +0,2 dano  •  +1 armadura  •  visão noturna",
                    List.of("30% de resistência a dano mágico", "H: Misty Step com pérola rápida", "Imunidade à queda após o teleporte")),
            race("kenku", "Kenku", "Imitador furtivo que se mistura às sombras e confunde criaturas com sons.",
                    "20 HP  •  110% velocidade  •  visão noturna",
                    List.of("Invisibilidade enquanto agachado", "H: imita um som de criatura", "Illagers não atacam"),
                    List.of("Villagers recusam trocas"), List.of()),
            race("harengon", "Harengon", "Explorador pequeno, veloz e sortudo, especializado em grandes saltos.",
                    "20 HP  •  110% velocidade  •  85% tamanho  •  visão noturna",
                    List.of("R: super pulo, recarga de 8s", "Ignora 5 blocos de queda", "30% de chance de drop extra de criaturas")),
            race("yuanti", "Yuan-Ti", "Serpente humanoide imune a venenos e resistente a magia.",
                    "22 HP  •  visão noturna", List.of("Imune a veneno", "30% resistência mágica", "H: Poison Spray")),
            race("kender", "Kender", "Pequeno aventureiro curioso, furtivo e extraordinariamente sortudo.",
                    "20 HP  •  110% velocidade  •  85% tamanho", List.of("15% de drop extra", "Invisível ao agachar", "H: Taunt")),
            race("khenra", "Khenra", "Guerreiro felino veloz que encadeia golpes contra o mesmo alvo.",
                    "22 HP  •  +0,1 dano  •  110% velocidade  •  visão noturna", List.of("Velocidade I constante", "Segundo golpe: +20% dano", "H: Twin Fury")),
            race("warforged", "Warforged", "Construto resiliente que não precisa comer.",
                    "24 HP  •  90% velocidade  •  110% tamanho  •  +2 armadura", List.of("Fome sempre cheia", "Regeneração I", "H: Integrated Protection")),
            race("vampire", "Vampiro", "Predador noturno que se nutre de seus inimigos.",
                    "20 HP  •  +0,1 dano  •  110% velocidade  •  visão noturna", List.of("Mordida desarmada cura", "H: Blood Drain"), List.of("Fraqueza e lentidão sob o sol"), List.of()),
            race("changeling", "Changeling", "Metamorfo capaz de se ocultar por meio de uma aparência ilusória.",
                    "20 HP  •  110% velocidade", List.of("H: Disguise Self (invisibilidade)")),
            race("siren", "Sereia", "Cantora aquática que controla os inimigos com sua melodia.",
                    "20 HP  •  visão noturna  •  +30% nado", List.of("Respiração aquática", "H: Charming Song")),
            race("hadozee", "Hadozee", "Ágil escalador que plana lentamente entre as alturas.",
                    "22 HP  •  110% velocidade  •  105% tamanho  •  visão noturna", List.of("Queda lenta", "Escala paredes agachado", "H: Glide")),
            race("giff", "Giff", "Hipopótamo marcial pesado, resistente a empurrões e mestre da besta.",
                    "26 HP  •  +0,1 dano  •  90% velocidade  •  120% tamanho  •  +2 armadura", List.of("50% resistência a empurrão", "+20% dano de besta", "H: Headbutt"))
    );

    private static RaceOption race(String id, String name, String summary, String attributes, List<String> abilities) {
        return race(id, name, summary, attributes, abilities, List.of(), List.of());
    }

    private static RaceOption race(String id, String name, String summary, String attributes,
                                   List<String> abilities, List<String> weaknesses, List<String> subraces) {
        return new RaceOption(id, name, summary, attributes, abilities, weaknesses, subraces);
    }
}
